[package]
name = "rust-websocket-client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
env_logger = "0.11.5"
futures = "0.3.31"
log = "0.4.22"
tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = "0.24.0"
